import type { AppState, Story } from "./types";
const base = {
  book_id: "demo",
  storyteller: "Eleanor",
  style: "first-person" as const,
  status: "published" as const,
  transcript: "",
  prompt: "",
  media: [],
  comment_count: 0,
  updated_at: "2026-08-20T12:00:00Z",
};
export const demoStories: Story[] = [
  {
    ...base,
    id: "demo-1",
    title: "The house with the blue door",
    prompt: "What did your childhood home feel like?",
    body: "The blue paint was my father's idea. Everyone else on our street had a perfectly sensible brown door, but he came home one Saturday with a tin of the brightest blue I'd ever seen.\n\nOur house was small, but it never felt that way to me. The kitchen always smelled of something baking, and there was a particular spot on the stairs where I could sit and hear everything without being seen.\n\nI used to think that home was the house itself. Now I think it was the sound of my mother's voice calling us in before it got dark, and knowing that when I opened that blue door, someone would be glad I was there.",
    position: 0,
    created_at: "2026-08-20T12:00:00Z",
    comment_count: 3,
  },
  {
    ...base,
    id: "demo-2",
    title: "Sunday, and the whole kitchen",
    prompt: "Which family recipe holds the most memories?",
    body: "Nobody ever wrote down my grandmother's recipe for Sunday bread. She measured flour with a teacup that had lost its handle and judged the dough by how it felt.\n\nMy job was to stand on a little wooden stool and turn the handle of the flour sifter. I took this responsibility very seriously. By the time the bread went into the oven, there was flour on the table, on my dress, and usually on the dog.\n\nI still make bread on Sundays. Mine is never quite like hers, but when the kitchen gets warm and that familiar smell starts, I am standing on that stool again.",
    position: 1,
    created_at: "2026-08-13T12:00:00Z",
    comment_count: 2,
  },
  {
    ...base,
    id: "demo-3",
    title: "A very long way to the sea",
    prompt: "Tell me about a road trip.",
    body: "We packed the car before the sun came up, with sandwiches wrapped in paper and a road map that had been folded too many times. My sister and I claimed opposite sides of the back seat.\n\nWhen we finally saw the water, none of us spoke for a moment. I had seen pictures of the sea, but I hadn't understood that it would keep going all the way to the sky. We ran down the sand without even stopping to take our shoes off.",
    position: 2,
    created_at: "2026-08-06T12:00:00Z",
  },
  {
    ...base,
    id: "demo-4",
    title: "How we found each other",
    prompt: "How did you meet the love of your life?",
    body: "I nearly didn't go to the dance. It had been raining all afternoon, and I'd convinced myself that staying home with a book was a much better idea.\n\nMy friend Ruth wouldn't hear of it. She arrived with an umbrella and said she'd stand in the doorway until I put my shoes on. I've thanked her for that stubbornness more times than I can count.",
    position: 3,
    created_at: "2026-07-30T12:00:00Z",
  },
  {
    ...base,
    id: "demo-5",
    title: "The things my garden taught me",
    prompt: "What is a hobby you could talk about for hours?",
    body: "The first thing I grew successfully was a row of radishes. I was so proud of them that I gave most of them away, which left us with almost none to eat.\n\nA garden has a way of reminding you that you can't hurry everything. You can water and weed and do your best, but some things happen in their own time. That turned out to be useful advice for the rest of my life, too.",
    position: 4,
    created_at: "2026-07-23T12:00:00Z",
  },
  {
    ...base,
    id: "demo-6",
    title: "A little courage goes a long way",
    prompt: "What would you tell your younger self?",
    body: "I would tell her to ask the question, even if she thinks everyone else already knows the answer. To take the trip. To tell people when they matter to her.\n\nAnd I would tell her that she doesn't have to know how the whole story goes before she takes the next step.",
    position: 5,
    status: "draft",
    created_at: "2026-07-16T12:00:00Z",
  },
];
export const demoState: AppState = {
  user: { id: "demo", name: "Alex Morgan", email: "alex@example.com" },
  books: [
    {
      id: "demo",
      title: "Eleanor's stories",
      storyteller: "Eleanor",
      cover_color: "#304c43",
      role: "owner",
    },
  ],
  book: {
    id: "demo",
    title: "Eleanor's stories",
    storyteller: "Eleanor",
    subtitle: "The little moments. The life they made.",
    dedication: "For the people who made it all worth remembering.",
    cover_color: "#304c43",
    role: "owner",
    recipient_email: "",
    phone: "",
    email_opt_in: false,
    sms_opt_in: false,
    reminder_day: 0,
    reminder_enabled: false,
  },
  stories: demoStories,
  questions: [
    {
      id: "q1",
      text: "What tradition would you love us to keep?",
      category: "Family & home",
      status: "queued",
      votes: 3,
      voted: false,
      expires_at: "2026-12-01",
    },
    {
      id: "q2",
      text: "Who was your very first friend?",
      category: "Childhood",
      status: "queued",
      votes: 2,
      voted: false,
      expires_at: "2026-12-01",
    },
    {
      id: "q3",
      text: "What journey changed how you saw the world?",
      category: "Life's adventures",
      status: "queued",
      votes: 1,
      voted: false,
      expires_at: "2026-12-01",
    },
  ],
  members: [
    { id: "demo", name: "Alex Morgan", email: "alex@example.com", role: "owner" },
    { id: "e", name: "Eleanor Morgan", email: "eleanor@example.com", role: "editor" },
    { id: "j", name: "James Morgan", email: "james@example.com", role: "viewer" },
  ],
  invitations: [],
  capabilities: { email: false, sms: false, storage: false },
};
