export const promptGroups: Record<string, string[]> = {
  Childhood: [
    "What did your childhood home feel like?",
    "Who was your very first friend?",
    "What did an ordinary summer day look like?",
    "What is a small kindness from childhood you still remember?",
    "What games could keep you outside until dark?",
    "What did you want to be when you grew up?",
    "Tell me about a time you got into trouble.",
    "What was your favorite place to hide?",
    "Who made you feel safe as a child?",
    "What did your neighborhood sound like?",
    "What did you save your pocket money for?",
    "What is your earliest memory?",
  ],
  "Family & home": [
    "Which family recipe holds the most memories?",
    "What do you remember about your grandparents?",
    "What tradition would you love us to keep?",
    "Tell me about a person in an old family photograph.",
    "What is the story behind your name?",
    "How did your family celebrate birthdays?",
    "What did your parents teach you without saying a word?",
    "What made your house feel like home?",
    "What family saying still makes you smile?",
    "Who was the storyteller in your family?",
    "What ordinary family moment do you wish you could revisit?",
    "Tell me about a meal that brought everyone together.",
  ],
  "Love & friendship": [
    "How did you meet the love of your life?",
    "When did you know you had found a lifelong friend?",
    "Tell me about a first date you will never forget.",
    "What have you learned about staying close to someone?",
    "Who has changed the course of your life?",
    "What is the most thoughtful gift you have received?",
    "Who made you laugh the hardest?",
    "Tell me about someone you miss.",
    "What is an adventure you shared with a friend?",
    "How did you stay in touch before smartphones?",
    "What does love look like in an ordinary day?",
    "What friendship surprised you?",
  ],
  "Life's adventures": [
    "What journey changed how you saw the world?",
    "When did you do something for the first time and surprise yourself?",
    "What is your favorite memory of being outdoors?",
    "Tell me about the most unexpected day of your life.",
    "What place would you return to in a heartbeat?",
    "What was it like to leave home?",
    "Tell me about a celebration you still remember clearly.",
    "What is a risk you are glad you took?",
    "What is the best thing that happened without a plan?",
    "What did you learn from living somewhere new?",
    "Tell me about a road trip.",
    "What was your first big adventure?",
  ],
  "Work & purpose": [
    "What was your very first job?",
    "Who saw something in you before you saw it yourself?",
    "What work are you most proud of?",
    "Tell me about a difficult decision that worked out.",
    "What did you learn from a mistake?",
    "What made you choose your path?",
    "What is a skill you learned the hard way?",
    "Who was your most memorable teacher?",
    "What would surprise us about your working life?",
    "When did you feel you were making a difference?",
    "Tell me about a dream you kept coming back to.",
    "What does a good day's work mean to you?",
  ],
  "Wisdom & legacy": [
    "What would you tell your younger self?",
    "What do you hope the next generation remembers?",
    "What has brought you the most joy?",
    "When was it hard to be brave, and how did you manage?",
    "What have you changed your mind about over the years?",
    "What does a meaningful life look like to you?",
    "What helped you through a difficult season?",
    "What are you still curious about?",
    "What is something you are grateful for today?",
    "What lesson would you like to pass along?",
    "What do you want your family to know about you?",
    "What story have I never thought to ask you about?",
  ],
  "Through the years": [
    "What did the world look like when you were a teenager?",
    "What song takes you right back to a moment in time?",
    "What invention changed your everyday life the most?",
    "How did you celebrate a milestone birthday?",
    "What was your favorite thing about being your age at twenty?",
    "What did becoming a parent or mentor teach you?",
    "What was a turning point you only recognized later?",
    "What is a hobby you could talk about for hours?",
    "Tell me about the clothes you loved to wear.",
    "What was the first big news event you remember?",
    "What has stayed the same about you?",
    "What part of getting older has surprised you?",
  ],
  "Behind the photograph": [
    "What happened just before this photo was taken?",
    "Who is outside the frame of this photograph?",
    "What can you remember about the place in this picture?",
    "What would the people in this photograph say about that day?",
    "Why did you keep this photograph?",
    "What is something this photo cannot show us?",
    "What happened to the people in this picture?",
    "What do you feel when you look at this image?",
    "What is the story behind an object in this photo?",
    "What would you tell the younger you in this picture?",
    "Who took this photo, and what were they like?",
    "What would you like us to remember about this moment?",
  ],
};
export const prompts = Object.entries(promptGroups).flatMap(([category, questions]) =>
  questions.map((text, i) => ({ id: `${category}-${i}`, category, text })),
);
